ALTER TABLE todos
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE todos
    ADD done BOOLEAN;

ALTER TABLE todos
    ADD title VARCHAR(255);

ALTER TABLE todos
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE todos
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE todos
    ALTER COLUMN updated_at SET NOT NULL;